ntryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  myresolver:
    acme:
      email: mjmax36@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
      # tlsChallenge: {}
# http:
#   routers:
#     my-router:
#       rule: "Host(`stox.systems`)"
#       entryPoints:
#         - web
#       middlewares:
#         - https-redirect
#       service: my-service

# middlewares:
#   https-redirect:
#     redirectScheme:
#       scheme: https
